PyAbel/PyAbel

- example.py
just indicated which code made the plots.
> Just added a comment to the example file

- BASEX/__init__.py
- BASEX/basis.py
- BASEX/core.py
- BASEX/io.py
- BASEX/tests/test_basis_set.py
- additional_files/basis_generating_matlab_programs/readme_matlab.txt
- examples/example_gausian.py
- examples/example_main.py
Cleaned up the code a little bit. Also, removed the shebang line (#!/usr/bin/python) at the top of the files, as discussed here: https://github.com/DanHickstein/pyBASEX/issues/6
> Code cleanup for v0.5

- README.md
- abel/basex.py
- abel/tests/run.py
- examples/example_step.py
Also, I removed “#!/usr/bin/python” from the top of abel/test/run.py
since it doesn’t seem necessary.
> A few small tweaks to the readme

- abel/tools.py
When I modified calc_speeds previously, I accidentally divided by two twice. I fixed that here.
> Fix speeds calc

- README.md
- abel/hansenlaw.py
updated readme to mention Hansen&Law transform. (Previously it said BASEX was the only option, which is no longer correct.)
> Readme update

- .gitignore
- CONTRIBUTING.md
- README.md
- abel/analytical.py
- abel/benchmark.py
- abel/tests/test_basex.py
- abel/tests/test_benchmarks.py
- abel/tests/test_hansenlaw.py
- abel/tests/test_tools.py
- appveyor.yml
- examples/example_basex_photoelectron.py
- examples/example_hansenlaw_basex.py
This Pull Request aims to discuss the contribution guidelines for adding new implementation in v0.7. This is relevant for issues #23, #24 , #27 , #30, and PR #35 .
It adds a [`CONTRIBUTING.md`](https://github.com/rth/PyAbel/blob/contribution_guidelines/CONTRIBUTING.md) which you can view with the previous link.
The general formulation and English might need to be revised, the main point of this PR is that I think that before merging an new fabel/iabel implementation to the code base it should pass some generic unit tests to check that it behaves as expected. 
Since the original developer is the person best suited to understand how his implementation work, I think it is better to detect inconsistencies with the general way PyAbel works before merging, rather then when the code is included …
> Discussion on the contribution guidelines and unit tests

- setup.py
When trying to upload to PyPi, I realized that I missed a comma in setup.py.
> Added a comma in setup.py

- abel/tests/test_tools_vmi.py
- abel/tools/analytical.py
- abel/tools/symmetry.py
- abel/tools/vmi.py
- examples/example_hansenlaw.py
- examples/example_simple_GUI.py
Code correction to the BASEX paper sample image function `abel.tools.analytical.sample_image_dribinski()` as per discussion issue #70.
*to do: add parameters to set image center, and provide for even image size*
> abel/tools/analytical.py sample_image_dribinski() code correction as per #70

- abel/__init__.py
- abel/basex.py
- abel/hansenlaw.py
- abel/tests/test_hansenlaw.py
- abel/tools/center.py
- abel/tools/symmetry.py
- abel/tools/vmi.py
- abel/transform.py
- doc/abel.rst
- examples/example_hansenlaw.py
This is just a few-line change to the AbelTransform class to address @stggh's concern about having too much in the __init__ function. The functionality is the same.
> Changes to the AbelTransform class

- abel/hansenlaw.py
I forgot to add this last change to the hansenlaw docstrings in the last PR.
> Hansenlaw docstring fix

- abel/basex.py
- abel/hansenlaw.py
- abel/three_point.py
- abel/tools/center.py
- abel/transform.py
- doc/abel.rst
- doc/conf.py
I’m slowly working my way towards getting the documentation to look nice. Here are some improvements to the Hansenlaw and transform.py docstrings.
Plenty of work left to go!
> Docstring improvements to hansenlaw and transform.py

- examples/example_three_point.py
@DanHickstein If you could verify that the three-point example compiles properly with these changes, that'd be great.
> Fix for broken three-point example

- abel/tools/center.py
- abel/transform.py
> passing center_options in transform

- .travis.yml
> set up travis CI to automatically deploy releases to PyPi

- abel/tools/vmi.py
> If `average` is `True`, don't use jacobian.

- abel/hansenlaw.py
This (simple) PR addresses issue #159 sub-pixel alignment for the `hansenlaw` method:
The offset was due to an incorrect definition of the normalized radius <math>(N-n)/(N-n-1)</math>
Discovered during a code clean up for execution speed enhancement, namely, the replacement of `np.power()` by the faster `**`
I have also changed:
1) `np.gradient` call with the `axis=-1` parameter, eliminating the image shape test for 2D
2) a couple variable names to match those used in the Hansen & Law paper: `Nm -> N`, `nn -> n`
3) removed the -0.3 pixel grid shift/interpolation
Bonus, inverse Abel transform now takes the same execution time as the forward transform
> hansenlaw -0.3 pixel offset

- abel/basex.py
- abel/benchmark.py
- abel/tests/test_basex.py
Enabled Tikhonov regularization in BASEX (see #225) and implemented RAM caching (see #226).
(Sorry, no unit tests.)
> Regularization and caching in BASEX

- CHANGELOG.rst
- examples/example_GUI.py
- examples/example_simple_GUI.py
This PR contains a few tweaks to make the GUI example successfully run. While we should make the GUI much better, I thought that I would start by making the existing GUI example actually work, since it's currently broken.
> Making the GUI example work again

- abel/transform.py
> Clarify purpose of symmetry_axis argument

- doc/transform_methods/comparison.rst
Following up on #306, this adds a brief discussion of the importance of background subtraction to comparison.rst.
> Included discussion of background subtraction in comparison.rst

- .travis.yml
- abel/__init__.py
- abel/benchmark.py
- abel/direct.py
- abel/tests/test_daun.py
- abel/tools/analytical.py
- abel/tools/center.py
- abel/tools/circularize.py
- abel/tools/math.py
- abel/tools/polar.py
- abel/tools/vmi.py
- examples/example_all_O2.py
- examples/example_all_Ominus.py
- examples/example_all_dribinski.py
- examples/example_hansenlaw_basex.py
I was playing with type hints and static code analysis ([mypy](https://mypy.readthedocs.io/en/stable/), to be specific) and found some minor errors and inconsistencies in our code (and docstrings), so here are their corrections...
> Some code and documentation improvements
