PyAbel/PyAbel

abel/benchmark.py, setup.py
Added a list of dependencies 
` "numpy >= 1.6"`,   ` "setuptools >= 16.0"`,   ` "scipy >= 0.14"`  
which should not be too constraining and we can lower the version numbers if needed. 
Checked that 
pip install git+https://github.com/PyAbel/PyAbel.git
works and the current tests pass on Linux and Windows (with conda). Same applies to `python setup.py install`  Pip will also try to install missing dependencies although in the case of numpy/scipy this might not be very desirable (compiling from sources is long).
=> Added a list of dependencies

abel/core.py
Following the issue #4 , this PR adds a fixed scaling factor of `8.053` on the output of the BASEX algorithm as to match the analytical results.
Here, I used the symmetric step function example (see PR #16 )  that depends on a number of parameters, including:
- `n` : number of points along the r axis
- `r_max`: range of the symmetric r interval
- `r1`, `r2`: bounds of the step function for (r > 0)
- A0:  height of the step
So the test code I used is accessible here https://gist.github.com/rth/9885931342bf8a5ad056 ( requires PR #16). Essentially, it calculates the ratio between the height of the reconstructed signal to the original one (e.i. the scaling factor). Then sweeps along different input parameters are performed in order to determine which ones influence the scaling factor. 
The …
=> Added a scaling factor to BASEX

abel/benchmark.py, abel/tests/test_benchmarks.py, abel/tests/test_tools.py, abel/tools.py
This PR adds unit tests for the centering function as to solve the issue discussed in issue #34 . 
It adds following functions,
-  `abel.tools.get_quadrants` :  a helper function to get the 4 quadrants of the image, as defined by @stggh implementation of Hassen&Law. The code is a bit different, but the result should be the same.
- `abel.benchmark.is_symmetric`: checks that an image is symmetric, with respect to its center (both for odd and even images). The symmetry center is defined in the discussion of the issue #34.
- `abel.tests.test_benchmark.test_symmetry_function`: some consistency tests for `is_symmetric`
- `abel.tests.test_tools.test_centering_function_shape`: check that `center_image` preserves shape (for odd and even images)
-  `abel.tests.test_tools.test_centering_function`: …
=> Add unit tests for the centering function

abel/tools.py
We will need to think more about centering, but in the short run, this PR fixes the bug where the center was shifted by one pixel for odd-sized imaged. The behavior is also correct for even-sized images (using the convention discussed in https://github.com/PyAbel/PyAbel/issues/34 if we return ``im[:-1,:-1]`` (Currently we are returning an odd-sized image even if we get an even sized image in. This seems good for what we currently know about basex, but in the long run we should change it to allow both even and odd images.)
Here is some code I used for testing:
```python
import numpy as np
import matplotlib.pyplot as plt
import abel
n=5
data = np.zeros((n,n))
data[2,2]=1
#
center = (2,2)
fig = plt.figure(figsize=(12,6))
ax1 = plt.subplot(121)
ax2 = plt.subplot(122)
d2 = …
```
=> Fixed centering function

abel/hansenlaw.py, abel/tools.py, examples/example_hansenlaw.py
The main issue is that ```reproject_into_polar()``` does not appear to handle even pixel sized images, due to the use of (integer,integer) coordinate centre, and associated ```np.meshgrid()```, as discussed in issue #39.  Edit: I take it back ```index_coords()``` accepts origin=(x,y). Just need to pass origin=(x,y) via tools.calculate_speeds()```, I think.
NB ```iabel_hansenlaw()``` performs the correct inverse Abel transform, so the code is still good to merge, with a caveat on the speed distribution, that is nearly correct.
=> Hansen and Law algorithm updates

abel/hansenlaw.py
Following the discussion in https://github.com/PyAbel/PyAbel/pull/49, this PR fixes the second-to-last line in the ``iabel_hansenlaw_transform`` function in order to allow the transform to work with non-square images. 
I am actually not sure if this line is even necessary. The center few pixels are noisy in either case, and I cannot really tell if there is a difference by eye. @stggh, does this line serve a specific purpose?
___
Also, I added a ``np.atleast_2d()`` statement to make ``iabel_hansenlaw_transform`` work if it's passed an array that is 1D (also changed the ``np.gradient`` to work for 1D). 
Does it make sense for ``iabel_hansenlaw`` to also work with 1D images? It will require a little bit of extra hacking, since the up/down quadrants concept doesn't apply. Right now, …
=> Making Hansen-Law transform work for non-square images

abel/tests/test_tools.py, abel/tools.py
This allows compatibility with the latest version of numpy (1.10.1), as discussed in https://github.com/PyAbel/PyAbel/issues/51. Only change was to explicitly cast ``nx`` and ``ny`` to floats in ``index_coords``. I think that they were being automatically being cast to floats previously, so the behavior should be the same.
=> Numpy compatibility

abel/benchmark.py, abel/dasch.py, abel/tests/test_three_point.py, abel/three_point.py
As discussed in #61, this pull request adds the 3-point Abel inversion technique to the repertoire of inversion algorithms available under PyAbel.
This technique was developed by [Dasch, 1992](https://www.osapublishing.org/ao/abstract.cfm?uri=ao-31-8-1146) (Applied Optics, Vol 31, No 8, March 1992, Pg 1146-1152). This algorithm exploits the observation that the value of the Abel inverted data at any radial position `r` is primarily determined from changes in the projection data in the neighborhood of `r`. 
From the paper: *the Abel integral is broken into segments around each point r<sub>j</sub>. In the neighborhood of each point,* the line-of-sight data *is expanded as a quadratic function of r - r<sub>j</sub>. Then each integral segment is integrated analytically. This method is called …
=> Implementing Three-point Abel - another inverse Abel transformation algorithm

abel/basex.py, abel/tests/test_basex.py
In this PR, 
- @stggh [raised](https://github.com/PyAbel/PyAbel/pull/72#issuecomment-181306117) the issue of core functions within `basex.py` not following the naming conventions of the other transform algorithm functions. To resolve this, I've renamed the main functions within `basex.py` according to the agreed conventions. I tried to follow @stggh's approach with `hansenlaw.py`, but I wasn't completely sure if the "wrapper" function should be named `iabel_basex(...)` (current) or `iabel_basex_transform(...)`. Any advice would be much appreciated.
- The `center` and `n` parameters for the `_abel_basex_core(...)` function (previously `BASEX(...)`) now have sensible default values. Only mandatory parameter is the image to be transformed. Docstrings updated to reflect appropriate changes.
- …
=> Clean up basex

.gitignore, abel/tools/__init__.py, abel/tools/symmetry.py, abel/tools/vmi.py, abel/transform.py, examples/example_simple_GUI.py
Here is a rough sketch of what the `abel.iabel` and `abel.fabel` classes could look like. They are both currently at `abel.transform.iabel` and `abel.transform.fabel`, but we could import them to `abel.iabel` in `abel/__init__.py`. 
Both the `abel.iabel` and `abel.fabel` classes are just child classes of the `abel.transform.abel_transform` class, so there is minimal code repetition. As you can see, all of the quadrants code has been shipped into this class, so it no longer needs to appear in the individual transform functions. 
@PyAbel/developers, have a look and see if this works for you. Let me know your suggestions.
@rth, I imagine that you may have already come up with something better, so I have no problem with you re-writing or replacing this PR. I just wanted to get the …
=> Preliminary format for abel.iabel and abel.fabel

abel/__init__.py, abel/basex.py, abel/hansenlaw.py, abel/tests/test_hansenlaw.py, abel/tests/test_tools.py, abel/tools/__init__.py, abel/tools/center.py, abel/tools/symmetry.py, abel/tools/vmi.py, abel/transform.py, doc/example_basex_gaussian.rst, doc/example_basex_photoelectron.rst, doc/index.rst, examples/example_basex_gaussian.py, examples/example_basex_photoelectron.py
As discussed in issue # https://github.com/PyAbel/PyAbel/issues/93, I converted the previous `transform.AbelTransform` class into the `abel.transform` function, which calls the other transform functions and returns a dictionary, where `results['transform']` is the 2D transform.
I also just called this `abel.transform` instead of using the `iabel/fabel` structure.
Other big changes:
1. I reformatted basex.py to get rid of all of the centering and speeds calculation stuff that we now do in the `abel.transform` function. 
2. I made some changes to `center.py`, trying to make everything in (y,x) (aka: row,column) format. 
3. I made `example_basex_photoelectron.py` and `example_basex_gaussian.py` work. I think that the rest of them are still broken.
4. I added some more to the docstring for …
=> Make abel.transform return a dictionary

abel/basex.py, abel/three_point.py
This PR adds the `direction` parameter to the function calls for `basex` and `three_point` as per the discussion in #96. 
@DanHickstein I hope I added the parameters in the right place.
=> Added dummy direction parameter to basex and three_point

CONTRIBUTING.md, abel/basex.py, abel/direct.py, abel/hansenlaw.py, abel/tests/test_basex.py, abel/tests/test_direct.py, abel/tests/test_hansenlaw.py, abel/tests/test_three_point.py, abel/tests/test_tools_center.py, abel/tests/test_tools_symmetry.py, abel/three_point.py, abel/tools/vmi.py, abel/transform.py, examples/example_O2_PES_PAD.py, examples/example_all_O2.py, examples/example_all_Ominus.py, examples/example_all_dribinski.py, examples/example_basex_gaussian.py, examples/example_basex_step.py, examples/example_direct_gaussian.py, examples/example_hansenlaw_basex.py
#96 and #103 removed `f/iabel_<method>` wrapper functions from all methods (except onion).
Repaired all `f/iabel` calls in `abel.<method>.py`, `abel.transform.py`, including doc strings, all unit tests, and all examples (phew!). 
All core functions are now `abel.<method>.<method>_transform()` with `direction="inverse/forward"` to transform right-side 1/2 or 1/4 image, and `abel.transform(method="<method>")` transforms the whole image.
IFAICT all unit tests and all examples run without error. 
NB:
@rth `test_direct.py` required a scaling factor to pass the unit test `test_inverse_direct_gaussian()`
@DhrubajyotiDas `example_basex_step.py`  the curves do not overlap
@DanHickstein, @ldes89150 please check the examples. I am not happy with Xe `hansenlaw` vs `basex`
=> Removal of f/iabel_<method> wrapper functions

abel/hansenlaw.py, abel/tests/test_tools_center.py, abel/tools/center.py, abel/transform.py, examples/example_GUI.py, examples/example_all_O2.py, examples/example_hansenlaw.py, examples/example_hansenlaw_basex.py, examples/example_simple_GUI.py
As per #109: 
>The maintain-size keyword would still make some sense, even if odd images are returned. The function could still approximately maintain the size and just return the closest odd sized image. I suggest that we add an odd_size=True keyword to set_center.
`abel.tools.center.py`:
* added parameter `odd_size=True` to `center_image()` to return an odd-width image if even.
NB  simply trims the right-most column, before the center is determined. @PyAbel/developers this may not be the best option (but, I think it is ...).
* integrated `find_image_center_by_slice()`, so that it is called by the common centering function,`find_center(IM, method='slice')`, and, now only returns the center coordinate tuple.
* updated unit test `tests/test_tools_center.py`, finding center by `slice` and …
=> center.py - return odd image width

abel/tools/analytical.py, abel/transform.py, doc/abel.rst, examples/example_all_Ominus.py, examples/example_basex_photoelectron.py, examples/example_hansenlaw_Xe.py
This addresses issues https://github.com/PyAbel/PyAbel/issues/117 and https://github.com/PyAbel/PyAbel/issues/119. 
It adds an options (which defaults to True) in `abel.transform` to recast the input image to `float64` to avoid problems with overflowing numbers in common image datatypes like `unit16`. 
Also, this changes the behavior of the sample_image function to keep the sample images the same size and shape as `n`, the number of points, is varied. I think that this is the desired behavior, because it's nice to compare how the transforms work as the sampling is changed, and this is only really possible if the image is remaining the same and only the sampling interval is changing.
The reason that I was working on this is that I would like to change all of the examples to use smaller …
=> recast images to float64 and keep sample_image constant zoom

abel/tools/analytical.py, abel/transform.py, appveyor.yml, doc/example_all_dribinski.rst, doc/examples.rst, examples/example_all_dribinski.py, examples/example_basex_gaussian.py, examples/example_basex_step.py
This PR fixes the `basex` step example. 
@DanHickstein Do you want me to reduce the `example_hansenlaw_basex.py` size to `n=301` in this PR as well?
=> Fix examples

CONTRIBUTING.rst, README.rst, abel/benchmark.py, doc/Makefile, doc/index.rst, doc/transform_methods.rst, doc/transform_methods/basex.rst, doc/transform_methods/comparison.rst, doc/transform_methods/direct.rst, doc/transform_methods/hansenlaw.rst, doc/transform_methods/onion_peeling.rst, doc/transform_methods/pop.rst, doc/transform_methods/three_point.rst, examples/example_hansenlaw_basex.py, examples/example_three_point.py
I am taking all of the descriptions of the transform methods out of the wiki and putting them into doc/transform_methods. I think that it looks really good as part of the documentation. 
Also, I made benchmark.py sort-of work again. It still needs some more work, and I'm done working on it for not. If @stggh or @DhrubajyotiDas want to take a look at it, that would be great. Currently, I think that it benchmarks the basis set generations as well as the transform methods 5 times each. This is probably too many times for the basis set generation, since this takes a long time anyway.
=> Getting benchmark.py working again and migrating the wiki

abel/three_point.py
As per [this comment](https://github.com/PyAbel/PyAbel/pull/128#issuecomment-191451302) in #128, `three_point.py` now features a `three_point_core_transform(IM, D)` function, which accepts the raw data `IM` and the `three_point` basis set, `D`, and returns the inverted image `inv_IM`. 
This functionality used to reside in `three_point_transform()` earlier, but has been specialized into its own function.
=> Added three_point_core_transform()

abel/benchmark.py
`abel.benchmark.py` update
- included `hansenlaw` forward transform,
- corrected print spacing for the output table
- corrected most pep8 warnings
```
python benchmark.py
PyAbel benchmark run on x86_64
=========     Direct Abel implementations ==========
time to solution [s] -> transform (basis sets generation)
Implementation |    n = 301          |    n = 501          
----------------------------------------------------------
direct_Python |  5.1e-02            |  2.3e-01            
HansenLaw |  2.1e-02            |  4.3e-02            
direct_C |  1.6e-02            |  7.1e-02            
=========    Inverse Abel implementations ==========
time to solution [s] -> transform (basis sets generation)
Implementation |    n = 301          |    n = 501 …
```
=> benchmark.py fixes

abel/hansenlaw.py, abel/tests/test_tools_center.py, abel/tests/test_tools_symmetry.py, abel/tools/center.py, abel/tools/symmetry.py, abel/tools/vmi.py, abel/transform.py, doc/transform_methods/hansenlaw.rst, examples/example_GUI.py, examples/example_O2_PES_PAD.py, examples/example_all_O2.py, examples/example_all_Ominus.py, examples/example_all_dribinski.py, examples/example_basex_gaussian.py, examples/example_basex_photoelectron.py, examples/example_basex_step.py, examples/example_direct_gaussian.py, examples/example_hansenlaw.py, examples/example_hansenlaw_Xe.py, examples/example_hansenlaw_basex.py, examples/example_simple_GUI.py
Updated docs for `doc/transform_methods/hansenlaw.rst` and `abel.tools.vmi.py`. 
NB I renamed `calculate_angular_distributions()` to `radial_integration()` to better align with the partner method `angular_integration()`.  Modified examples to suit.
Hmm, some of the listed changes were just a 80 column reformat, sorry.
@DanHickstein `livehtml` is neat, and certainly speeds up the editing process.
Edit: NB changed name of parameter `method` to `center` in `abel.tools.center.find_center(image, center="<method>")` to match `center_image(image, center="<method>")`
=> doc update for hansenlaw, vmi

MANIFEST.in, abel/basex.py, abel/three_point.py, examples/example_basex_step.py, setup.py
This is following up on the benchmarking discussion in https://github.com/PyAbel/PyAbel/issues/136. Apparently, the functions (like `dot` and `inv`) in scipy.linalg use a fortran version of LAPACK, which is compiled from fortran. Numpy uses some implementation of BLAS/LAPACK, and the implementation depends on the OS and the python distribution. In most cases (Apple’s Accelerate framework on OS-X, Intel’s MKL libraries in Anaconda, and openBLAS), numpy is just as fast as scipy. However, there are cases where numpy uses versions of BLAS and LAPACK that are not optimized and provide much slower behavior. Since scipy is a requirement anyway, then it makes sense that we just use scipy.
More info:
http://www.scipy.org/scipylib/faq.html#why-both-numpy-linalg-and-scipy-linalg-what-s-the-difference …
=> switched linalg from numpy to scipy in basex and three point

abel/tests/test_direct.py, abel/tests/test_transform.py, abel/tools/polar.py, abel/tools/vmi.py, abel/transform.py
Implemented angular integration (speed distribution) into `abel.transform()`, and updated docs.  
`abe.transform()` now also returns `['angular_integration']` data.
Q: @DanHickstein should I update the `__main__` example at end of the `transform.py` file to use the this call format? 
additional parameters:  `angular_integration=True/False`
`angular_integration_options=dict()`
e.g.
```python
import numpy as np
import abel
import matplotlib.pyplot as plt
IM = np.loadtxt("examples/data/O2-ANU1024.txt.bz2")
res = abel.transform(IM, center="slice", method="hansenlaw", direction="inverse", angular_integration=True)
plt.plot(*res['angular_integration'])
plt.show()
```
=> Implement angular_integration  into abel.transform()

abel/benchmark.py, abel/hansenlaw.py, abel/tools/vmi.py, examples/example_all_O2.py, examples/example_all_dribinski.py, examples/example_hansenlaw.py
Using the magic of `np.power()` to replace `pow()` allows some vectorization improvement to the `hansenlaw` algorithm.  I imagine/hope these types of code changes may be taken further ...
- removes 'k' for loop
```python
for k in range(K):  # Iterate over k, the eigenvectors?
X[:, k] = pow(Nm, lam[k])*X[:, k] +\
h[k]*gamma(Nm, lam[k], n)*gp[:, n]  # Eq. (15 or 17)
```
- (apparently) no longer requires the pseudo 1-column shift - e.g. run `examples/example_all_O2.py`
```python 
#for some reason shift by 1 pixel aligns better? - FIX ME!
if direction == "inverse":
AIM = np.c_[AIM[:, 1:],AIM[:, -1]]
```
- faster execution  ~30% improvement (`n=501`) cf [PR #155](https://github.com/PyAbel/PyAbel/pull/155#issuecomment-203097576)
```
In [2]: abel.benchmark.AbelTiming(n=[301, 501, 1001])
Out[2]: …
```
=> hansenlaw vectorization with np.power()

abel/dasch.py
`dr` grid size intensity scaling parameter was not passed to the respective `two_point`, `three_point`, and `onion_peeling` transforms
=> dasch bug fix 

abel/tools/vmi.py
Because in VMI imaging processing, we always use the correct Jacobian r*sin(theta) term when doing Abel inversion.
Yuan
=> Change the default of angular_integration() from Jacobian=False to Jacobian=Ture in tools/vmi.py

.travis.yml, abel/linbasex.py, abel/tests/test_tools.py, abel/tools/vmi.py, abel/transform.py, doc/anisotropy_parameter.rst, doc/index.rst, examples/example_GUI.py, examples/example_O2_PES_PAD.py, examples/example_PAD.py, examples/example_basex_photoelectron.py, examples/example_dasch_methods.py, examples/example_linbasex_hansenlaw.py, examples/example_simple_GUI.py
From issue #176. This is really @DanHickstein's baby, that I somehow hijacked.  It simply allows the determination of the anisotropy parameter for a radial grid, determined from @DanHickstein clever code [example](https://github.com/PyAbel/PyAbel/issues/176#issue-153615099):
```python
r = np.arange(0,300,2)
r_range = list(zip(r[:-1], r[1:]))
```
In this PR I have:
1. Created new function `abel.tools.vmi.anisotropy()` to provide a single call to obtain the anisotropy parameter. Previously, 2 steps were required, one to evaluate intensity vs angle (for a given radial range) `abel.tools.vmi.radial_integration()`, the second to evaluate the anisotropy parameter from a fit to the intensity variation `abel.tools.vmi.anisotropy_parameter()`. See `examples/example_O2_PES_PAD.py`
2. Modified …
=> anisotropy versus radial coordinate

appveyor.yml, setup.py
This PR fixes issue #183 (and possibly #125, if that was still an issue) with the compilation on Windows. All windows builds are tested again, which takes some time with appveyor but is probably safer.
The solution was to remove the `libpython` (mingw compiler) from the list of installed packages so that the already present Visual Studio compiler gets used. 
Also removing all flags to hide warnings (as those might actually be useful),  reverting to the default flags.
=> FIX Cython extension not building on Windows

examples/example_linbasex.py
@DanHickstein [synopsis](https://github.com/PyAbel/PyAbel/pull/195#issuecomment-282856378) of `readthedocs` build failure for PR #195 :
The docs failed to build on readthedocs again: https://readthedocs.org/projects/pyabel/builds/5081882/
Same issue with memory on the example_linbasex.py.
We need to change line 19 from
```python
if os.environ.get('READTHEDOCS', None) == True:
```
to
```python
os.environ.get('READTHEDOCS', None) == 'True'
```
(The os.environ.get returns a string instead of a Boolean, apparently. Tricky.)
=> fix for readthedocs build fail: memory requirements of example_linbasex.py

abel/tests/test_tools_center.py, abel/tests/test_tools_circularize.py, abel/tools/center.py
This PR:
- adds a new parameter `axes` to `abel.tools.center.set_center()` and its calling function `abel.tools.center_image()`, to apply the center correction only for the axis specified. It provides for automatic centering  (`com`, `convolution`, `slice`) if the image is symmetric along only one axis.
- Bug fix: `crop` parameter was in the docs of `center_image()`but not listed as an argument, or passed to `set_center()`.
I anticipate a discussion on whether the new parameter `axes` should be the axis along which the centering is applied (at the moment), or the axis of symmetry ...
=> Center image along one axis

abel/basex.py, abel/benchmark.py, abel/dasch.py
As discussed in https://github.com/PyAbel/PyAbel/issues/207, I think that it makes the most sense for the benchmarks to operate on square whole-images that possess left/right symmetry. Prior to this PR, `abel.benchmark.AbelTiming(n=[101])` completes a 101x101 transform, which actually corresponds to a transform of a left/right symmetric 101x201 image.
This PR changes that behavior, and completes a transform on the 101x51 half-image. It should make most of the benchmarks faster, since they are operating on a smaller image. BASEX and LinBasex operate on whole images, so they are passed the complete image and maintain their previous benchmark speeds.
=> Changing the benchmarks to operate on square whole images

README.rst, abel/direct.py, abel/lib/direct.pyx
As discussed in #213 (which followed from our discussion in #211), we decided that the `direct` method was using a "even" grid (`[0.5, 1.5, 2.5, ...]`). I switched one line so that it now operates on an "odd" grid (`[0, 1.0, 2.0, ...]`). 
I also cleaned up a few lines of comments towards the top of `direct.py`.
=> Fixed the grid for the direct method

abel/benchmark.py
`time.time` has only a  ~16 ms precision on Windows and `time.clock` is more appropriate there.
This switches to using `timeit.default_timer` which takes the best available timer automatically.
=> Use better timer for benchmarks on Windows

abel/basex.py, abel/benchmark.py, abel/dasch.py, abel/linbasex.py, abel/tests/test_basex.py, abel/tests/test_tools_polynomial.py, abel/tools/__init__.py, abel/tools/analytical.py, abel/tools/polynomial.py, doc/abel.rst, doc/conf.py, setup.py
This addresses all issues in #230 and finalizes #226.
The basis-generation code (`_bs_basex()`) is rewritten almost completely.
- Now it works with arbitrary width parameters _σ_ and accepts `n, sigma` instead of `n, nbf`. `sigma` is actually used everywhere, since it is more fundamental than `nbf` (which is `n` / `sigma`).
- The computations became is >10 times faster:
- All the needed Γ-function values are precomputed, which takes _O_(_n_<sup>2</sup>) extra space (~the same as for the basis matrices), but avoids recomputing them _O_(_n_<sup>3</sup>) times.
- The summation cutoff is tightened very close to the limit for "numerically exact" results (floating-point precision).
- It can take previously computed smaller basis matrices for the same _σ_ and extend them by computing only the …
=> BASEX improvements

.zenodo.json, CONTRIBUTING.rst
I'm still trying to get the automatic publishing of new releases to Zenodo to work.
For v0.8.0, we got the following response from Zenodo:
```
{
"errors": "Unknown error occured."
}
```
which is super helpful. This was the "payload" delivered to Zenodo from GitHub [[gist link](https://gist.github.com/DanHickstein/e6a840e1e2d2adccda8811cf467a77d0)]
I then realized that many of the author names on Zenodo for v0.7.6 were just the github user names, and not our real names. I figured out that we can make a `.zenodo.json` file in out repository that contains our corrected names.
Then, I released v0.8.1, and got the following error:
```
{
"errors": "Metadata file \".zenodo.json\" is not valid JSON."
}
```
Which is legit, because I had some extra commas in the .json file. I removed these, and …
=> Trying to fix zenodo releases

abel/basex.py, abel/tests/test_basex.py
This adds the forward Abel transform to the BASEX method.
The basic idea is that since the projected image and its reconstruction are described by the same coefficients, but in different basis sets (related to each other through the forward/inverse Abel transform), swapping these basis sets and applying the same method reverses the transform direction.
Then there are some technical details related to the _dr_ scaling and what to use for the intensity correction.
`cache_cleanup()` now accepts an optional parameter for selective cache purging. For example, it is possible to do a forward transform, discard its matrix, keeping the basis set cached, and do an inverse transform. By default, it still purges everything.
I've added new tests for the forward transform, but no benchmarks, since they …
=> BASEX forward transform

README.rst
This is in response to https://github.com/PyAbel/PyAbel/issues/242. 
So far, I think that the only update is that we need to change the link to the badge in README.rst from .org to .com. Part of this PR is a test to see if we can successfully trigger builds on travis-ci.com.
=> Updates to convert from travis-ci.org to travis-ci.com

abel/benchmark.py
This is the reworked `abel.benchmark.AbelTiming`.
The main changes are related to the basis caching now used by all the basis-set methods, plus that `basex` also got the forward transform (and variable regularization, as previously addressed in the experimental [bench-var](https://github.com/MikhailRyazanov/PyAbel/tree/bench-var)). It also implements the “run for at least _n_ seconds” idea, which help to get more stable results for fast stuff without running the slow stuff too many times.
Since it turned out that different methods require somewhat different benchmarking procedures, I have created here an individual function for each method, which benchmarks everything related to that method (basis-set generation, forward and inverse transforms — as applicable). This makes the code more …
=> New benchmark code

abel/hansenlaw.py, abel/onion_bordas.py
For `hansenlaw` evaluate the image row gradient as a first-order finite difference, as per @MikhailRyazanov suggestion:
> Well, in one dimension, “gradient” is the derivative. But I see that PyAbel actually calculates it using numpy.gradient, which assumes “that f ... has at least 3 continuous derivatives” — I think, this is way too much to expect from any experimental data.
> Basically, the problem is that NumPy uses the two-sided formula to estimate the derivative at the grid points, whereas our integral (2) actually needs the derivatives within the integration intervals. I suspect that using the standard first-order finite differences and choosing the integration points half-way between the image sample points will work better. For the “direct” method at least, I don't know how the …
=> hansenlaw with gradient calculated as a first-order finite difference

abel/benchmark.py
1. For convenience, multiple image sizes (`n=...`) can now be passed as `numpy.ndarray` (or any other object convertible to Python's `list`). The previous implementation required multiple sizes to be passed as a list and was producing not very helpful error messages otherwise.
2. Some people try to use `abel.benchmark.AbelTiming` for very large image sizes, and if it runs out of memory, the program crashes, losing all the previous results. To avoid that, the `MemoryError` exception is now handled in the same way as `SIGINT` (Ctrl+C), skipping the rest of the benchmarks, but preserving the existing results.
I have only tested that this memory handling works in Linux when the requested size is too large.
If anybody is willing to test it in Windows and macOS, and also how it works (in all …
=> New benchmark code (update)

abel/tools/analytical.py
A correction for the mistakenly coded width of the background Gaussian in `abel.tools.analytical.SampleImage._dribinski()`.
The expression in the original article looks like exp[−(_R_ − 45)<sup>2</sup>/3600], whereas our implementation defines Gaussians as `np.exp(-(r-r0)**2/sigma**2)` and uses `sigma=3600`, which actually leads to exp[−(_R_ − 45)<sup>2</sup>/3600<sup>2</sup>], an extremely broad (almost flat) background. Changing this to `sigma=60` produces the correct result.
Radial intensity distributions (integrated over the full solid angle):
Before:
After:
From the original article (solid line):
Plus, the docstring is modified to clarify what these “widths” actually are (and slightly reformatted).
=> Correct background width in Dribinski sample image

abel/benchmark.py, abel/hansenlaw.py, abel/tests/test_tools_distributions.py, abel/tools/vmi.py, doc/anisotropy_parameter.rst, doc/conf.py, examples/example_anisotropy_parameter.py
This is the implementation of various radial distributions (intensity, anisotropy), discussed in #254.
(Plus some minor changes to code and docstrings formatting and the updated copyright years.)
Works for any image parts (any quadrant, any half, full image with the origin anywhere) and any even angular orders. Also is fast:
```
order = 2, time in milliseconds
=== Half image, single ==========================================
Method                n = 257     n = 513    n = 1025    n = 2049
-----------------------------------------------------------------
nearest
MIN, none              2.0         5.4        18.1        52.5
MIN, sin               2.0         6.2        20.2        55.7
MIN, sin+array         2.1         6.5        21.5        62.3
linear
MIN, none              2.3 …
```
=> Various radial distributions

abel/basex.py
As noticed in #259, recent versions of NumPy switched the default parameters of `numpy.load()` to `allow_pickle=False`, which makes any attempts to load `basex` cache files always fail and thus triggers basis-set generation every time. The problem is that the PyAbel version (`__version__`) is saved in the cache files, and NumPy need to “pickle”/“unpickle” this _string_, so `allow_pickle=True` is required in the `load()` functions. This was actually the default behavior, but now is disabled by default (allegedly, due to security reasons).
However, this version string, although saved and loaded, is in fact not used for any purposes. And other Abel methods do not even write it to their cache files. So, I think, the best solution is just to drop it from `basex` cache files, which is done in …
=> Drop PyAbel version from BASEX cache files

CHANGELOG.rst, abel/tests/test_tools_distributions.py, abel/tools/vmi.py, doc/changelog_link.rst, doc/conf.py, doc/index.rst
This is (finally!) an implementation of odd angular orders for the anisotropy distributions, to finish with #254 and address #265.
The behavior and performance for even orders (still the default mode) should not be affected, but odd terms can now be included by specifying `odd=True` after `order` or supplying an odd `order`.
An example with pure Legendre polynomials:
```python
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
from abel.tools.vmi import Distributions
fig = plt.figure(figsize=(16, 8))
R = 150
n = 2 * R + 1  # width
m = 2 * R + 1  # height
x0 = R; y0 = R  # center
x = np.arange(float(n)) - x0
y = y0 - np.arange(float(m))[:, None]
r = np.sqrt(x**2 + y**2)
r[y0, x0] = np.inf
s = x / r
c = y / r
r[y0, x0] = 0
sigma = 5.0  # peak SD
step = 5 * …
```
=> Odd orders for abel.tools.vmi.Distributions

CHANGELOG.rst, README.rst, abel/__init__.py, abel/benchmark.py, abel/rbasex.py, abel/tests/test_rbasex.py, abel/tests/test_tools_distributions.py, abel/tools/vmi.py, abel/transform.py, doc/abel.rst, doc/anisotropy_parameter.rst, doc/example_rbasex_block.rst, doc/example_rbasex_multimass.rst, doc/examples.rst, doc/transform_methods.rst, doc/transform_methods/rbasex-SVD.py, doc/transform_methods/rbasex-bR.py, doc/transform_methods/rbasex-coord.py, doc/transform_methods/rbasex-limits.py, doc/transform_methods/rbasex-math.rst, doc/transform_methods/rbasex-pRn.py, doc/transform_methods/rbasex-peak.py, doc/transform_methods/rbasex-regRMSE.py, doc/transform_methods/rbasex-sim.py, doc/transform_methods/rbasex.rst, doc/transform_methods/rbasex_reg.py, examples/example_GUI.py, examples/example_rbasex_block.py, examples/example_rbasex_multimass.py, examples/example_simple_GUI.py
Here is a new method for analyzing velocity-mapping images, similar to pBasex, but implemented more efficiently.
The main idea is that the Abel transform of _f_(_r_) cos<sup>_n_</sup> θ is _F<sub>_n_</sub>_(_r_) cos<sup>_n_</sup> θ, with some other radial part _F_<sub>_n_</sub> (different for different powers _n_) but the same angular dependence. And if a suitable basis is chosen for the radial part, the forward transforms _f_(_r_) → _F_<sub>_n_</sub>(_r_) can be computed analytically for all _n_. The rest is as usual in all “BASEX”-type methods.
That is, to perform a forward or inverse Abel transform of an image, it is sufficient to extract from it the radial profiles of all cos<sup>_n_</sup> θ terms, transform these radial profiles (which is much faster that transforming the whole …
=> rBasex, a better pBasex

.travis.yml, appveyor.yml
As @MikhailRyazanov pointed out (#271 (comment)), we should be testing with the latest version of Python (3.8). I removed the tests for Python 3.6, since I think that testing on three Python versions is enough (2.7, 3.7, 3.8). 
(I know that @stggh will argue that we drop the Py2.7 test. He's probably right. Maybe we keep Py2 compatibility and testing through 2020 and we can celebrate New Years by going all Py3?)
=> included python 3.8 tests

CHANGELOG.rst, examples/example_GUI.py
Here is the correction to `example_GUI.py` that lets it run without the `'bases'` directory, as discussed in #275. Moreover, now it catches all exceptions occurring in `Transform()` and shows them in the GUI messages pane, so that if something wrong happens, the user will surely notice that.
Another problem was that loading "from transform" in fact did not work, since the code assigned the `Transform` object instead of its transformed image (`.transform`). This is also corrected (and seems to work).
Please test.
=> Corrections to example GUI

CHANGELOG.rst, CONTRIBUTING.rst, abel/tests/test_tools_circularize.py, abel/tools/circularize.py, abel/transform.py, doc/circularize_image.rst, examples/example_circularize_image.py
This is to address #276 — switching to periodic splines to avoid possibly discontinuous corrections at ±π, and also switching from the raw `smooth` parameter for spline smoothing to the more meaningful RMS tolerance.
=> Circularization improvements

README.rst, abel/rbasex.py, abel/tools/vmi.py
While the new release (#292) is still pending, let's do some minor things...
1. Reformat the methods list in README such that GitHub does not render it like a quote (see [here](https://github.com/PyAbel/PyAbel/issues/292#issuecomment-631613447)).
2. Add a warning to `tools.vmi.Distributions` and `rbasex.rbasex_transform` that using high angular orders can lead to poor results (partially addresses #286).
=> Minor documentation improvements

CHANGELOG.rst, abel/tests/test_tools_center.py, abel/tools/center.py, doc/tools/crop_options.py
OK, here is the `abel.tools.center.set_center()` rewritten completely:
* Should behave correctly for all reasonable parameters.
* Doesn't lose fractional edge pixels (`scipy.ndimage.shift()` is [going](https://github.com/scipy/scipy/issues/12773) to be corrected eventually, but this works with what we have now).
* Allows selecting the interpolation order.
* Includes a much faster implementation without interpolation.
* Allows specifying `None` in the origin for axes that do not need centering.
Also, the `axes` argument is added to `find_origin...()` methods, such that they don't do unnecessary (and potentially unsuccessful) work. Now they return the image center coordinate for unused axis, so passing this to `set_center()` will have no effect.
=> New set_center() implementation and axes in find_origin()

.travis.yml, README.rst, appveyor.yml, setup.py
Per the discussion on #307, I did the following:
- I updated the Travis tests to Py3.9
- I updated the Ubuntu version to `focal` for the Py3.9 test (leaving the 3.8 test with `xenial`)
- I removed the 32-bit Py3 builds on Appveyor, to speed things up. (Appveyor tests are still completed in serial and take about 2.5 minutes each. So, dropping from 6 to 4 tests speeds up out test time from 15 mins to 10 mins.)
- I left the Appveyor at 3.8, since it seems that Py3.9 isn't available yet: https://docs.conda.io/en/latest/miniconda.html
- I updated the supported versions in the README, and included a note warning that Py2 support may be dropped soon (this one is for you @stggh!). 
- I included py3.8 and py3.9 as supported versions in setup.py so that these will show up on PyPI.
=> Update Travis tests to Py3.9

CHANGELOG.rst, abel/direct.py, setup.py
Following the discussion in #308, we decided that we should move the `import numpy as np` line into the `try` block in setup.py. Numy is required for the `np.get_include()` command to build the Cython extensions.
This should allow pip to successfully install PyAbel, even in situations where numpy was not previously installed.
I'll work on adding something to the readme to discuss the Cython+numpy+C-compiler for building the direct-C.
=> Moving numpy import into try block in setup.py

CHANGELOG.rst, abel/__init__.py, abel/tests/test_dasch_methods.py, abel/tests/test_hansenlaw.py, abel/tests/test_linbasex.py, abel/tests/test_tools_vmi.py, abel/tools/analytical.py, abel/tools/math.py, abel/tools/polar.py, abel/tools/polynomial.py, abel/tools/transform_pairs.py, abel/tools/vmi.py, abel/transform.py, doc/transform_methods/basex-basis.py, doc/transform_methods/comparison/fig_experiment/experiment.py, examples/example_GUI.py, examples/example_O2_PES_PAD.py, examples/example_all_O2.py, examples/example_all_Ominus.py, examples/example_all_dribinski.py, examples/example_basex_photoelectron.py, examples/example_circularize_image.py, examples/example_dasch_methods.py, examples/example_hansenlaw_Xe.py, examples/example_hansenlaw_basex.py, examples/example_onion_bordas.py, examples/example_rbasex_block.py, examples/example_rbasex_multimass.py, examples/example_simple_GUI.py
Here are the new functions:
* `angular_integration_2D()` and `angular_integration_3D()` to replace `angular_integration()`,
* `average_radial_intensity_2D()` and `average_radial_intensity_3D()` to replace `average_radial_intensity()`.
They are in fact implemented through a new function `radial_intensity()`, which can do all of this.
The old functions are declared deprecated and removed from the rest of the code. Hopefully, completely... This took most of the effort. :–) In this process, I've discovered one **problem**: the `angular_integration` option in `transform.Transform()` was using that incorrect `angular_integration()` function and thus also produced incorrect results. I've [mentioned this in the docstring](https://github.com/MikhailRyazanov/PyAbel/blob/d8173987ac044649216788482be8c …
=> New functions for angular integration and average

CHANGELOG.rst, CONTRIBUTING.rst, README.rst, abel/benchmark.py, abel/dasch.py, abel/hansenlaw.py, abel/linbasex.py, abel/onion_bordas.py, abel/transform.py, doc/circularize_image.rst, doc/conf.py, doc/transform_methods/rbasex-coord.py, examples/README.txt
Addressing #321: a short README.txt file in the `examples` directory to clarify that the scripts should be run _there_.
And minor corrections to the v0.8.4 release information:
* Updating the copyright years.
* Correcting the release date (was 2020 instead of 2021) in the changelog.
=> README file for the examples directory + years corrections

CHANGELOG.rst, abel/transform.py
1. Some `dict` parameters of `abel.transform.Transform` had incorrectly documented types (tuples really don't work there).
2. With `symmetry_axis=(0, 1)`, instead of transforming 1 quadrant, it was calling underlying transform methods for 3 quadrants (but using only 1 of them).
=> Corrections to Transform()

.travis.yml, setup.py
Following https://github.com/PyAbel/PyAbel/issues/323, we should enable testing on MacOS is possible. TravisCI seems to support this. 
I think that we just need to edit the `.travis.yml` file. This is my first attempt. Will probably take a few iterations.
=> Enabling OSX testing on travis

CHANGELOG.rst, abel/basex.py, abel/tests/test_dasch_methods.py
Some changes related to `basis_dir`, overlooked in the previous PR #327:
* The `dasch` unit tests were failing unless ran on a clean system (the disk-cache test tired to delete a temporary file using a wrong path; reported in #335). Now they avoid using disk caching unless absolutely necessary, and when needed, use the local `tests/data` subdirectory for these temporary files, like all other tests do, and also clean-up after themselves.
* There was a strange error in `basex` when using a relative path for `basis_dir` and running Python 2 (in this case `glob()` yields relative paths). I'm surprised how it was working and passing all tests...
=> Repairs to basis_dir (amending #327)

README.rst, doc/overview.svg
OK, offline HTML at RTD seems to be working (although not without surprises, see https://github.com/readthedocs/readthedocs.org/issues/9068).
This is the second part of #348, replacing README image links with absolute URLs such that they can be used on PyPI (hopefully).
=> Offline HTML (2nd iteration)

.travis.yml, CHANGELOG.rst, abel/benchmark.py, abel/linbasex.py, abel/tests/test_benchmarks.py, abel/tests/test_linbasex.py, abel/transform.py, appveyor.yml, doc/conf.py, doc/transform_methods/comparison/fig_experiment/experiment.py, examples/example_GUI.py, examples/example_all_O2.py, examples/example_all_dribinski.py, examples/example_anisotropy_parameter.py, examples/example_linbasex.py, examples/example_linbasex_hansenlaw.py, examples/example_simple_GUI.py
These are the changes related to `linbasex` as discussed in #356, plus some other minor corrections (repair of `verbose` in `Transform()` and some corrections to the examples).
One thing that I'm not sure about is the docstring for `linbasex_transform()`. Previously it was shared with `linbasex_transform_full()` (see `_linbasex_parameter_docstring`), but there are in fact too many important differences for such mechanical treatment. Thus for `linbasex_transform()` I've simply documented its unique parameters and referred to the main function `linbasex_transform_full()` for the rest. But maybe every parameter must be documented for completeness? Or maybe it would be easier/better to replace them all with `**kwargs` and say that additional arguments are passed to …
=> Linbasex changes

.travis.yml, abel/tests/test_tools_transform_pairs.py, abel/tools/math.py, abel/tools/transform_pairs.py, setup.py
I've noticed that we don't have CI tests with Python 3.10 (the current version, released almost a year ago), so this PR adds it for Travis testing (3.10 should now also be available at AppVeyor, but it's working so slowly that I'm not sure whether having more jobs there would be justified).
The testing coverage report, repaired in #357, also showed that transform pairs are not tested at all, so I've made basic tests for them. This also highlighted potential problems with the profiles that have discontinuities, so I've also added some notes to their descriptions.
And another small clean-up inspired by type-hinting exercises: `guss_gaussian()` from `tools.math` is renamed to `guess_gaussian()` — I suspect that “guss” was an accidental misprint rather than something meaningful.
=> Testing: Python 3.10 and transfrom pairs

.travis.yml, CONTRIBUTING.rst, README.rst, appveyor.yml, doc/readme_link.rst, setup.py
I think, it would be a good time to release a new version soon, so here are some changes to address some of the remaining issues.
As reported in #354, linking from the stable distribution to our development documentation ("latest") is confusing. However, the description displayed on PyPI (and included in the package) is defined in `setup.py` by the `long_description` variable and can be adjusted, so I've added some simple code to replace all "latest" GitHub and RTD links in README with links to the particular version. I've checked the results as descibed in https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/, and they seem correct. Hopefully, this will work properly when released (for example, the versioned "example" picture doesn't exist yet, but it should be …
=> Tweaks for documentation and PyPI

.travis.yml, CHANGELOG.rst, abel/_version.py
OK, another attempt, with the Travis config corrected (also moving `deploy:` to just the latest Python version, since otherwise `before_deploy: sleep 5m` was uselessly executed for each build).
The release noted will be moved from #364.
=> Preparations for v0.9.0rc2 release (v0.9.0 pre-release)

.travis.yml, CHANGELOG.rst, abel/_version.py
Hopefully, the last attempt to repair Travis deployment (see https://github.com/PyAbel/PyAbel/issues/361#issuecomment-1341389560) before the final release...
Release noted will be moved from [v0.9.0rc2](https://github.com/PyAbel/PyAbel/releases/tag/v0.9.0rc2).
=> Preparations for v0.9.0rc3 release (v0.9.0 pre-release)

README.rst, doc/conf.py
To address #371, the deprecated `python setup.py` instructions are replaced with the recommended `pip install .`.
(My local Sphinx now also complains about `language = None`, so I've put the actual `'en'` there, as it suggested.)
=> Update installation commands

.readthedocs.yml, CONTRIBUTING.rst, abel/tools/center.py, doc/conf.py, doc/requirements.txt, doc/transform_methods/rbasex-coord.py
I've got an email from Read the Docs that they'll soon deprecate the “use system packages” feature, which for us means that `matplotlib` will not be available preinstalled, so we need to install it explicitly. This also applies to `numpy` and `scipy`, but these are already listed as dependencies for `pyabel` itself and hopefully will be installed as needed...
=> Specify requirements for Read the Docs

abel/direct.py, abel/tools/vmi.py, doc/transform_methods/comparison/fig_benchmarks/throughput.py, doc/transform_methods/comparison/fig_experiment/experiment.py
NumPy is planning to release v2.0 soon (conda already wanted to rebuild for it, see https://github.com/conda-forge/pyabel-feedstock/pull/27). I've tested locally with `numpy 2.0.0rc2` (from PyPI) and found that small modifications are needed to ensure compatibility with it:
* `numpy.trapz()` was renamed to `numpy.trapezoid()`, so we'll need to use the one that is available (`numpy.trapezoid()` isn't available in current versions, so we can't just switch to it; `scipy.integrate.trapezoid()` wasn't present in `scipy 1.2` — the last available for Python 2).
* `numpy.NaN` (used only in one documentation figure) was removed, so `numpy.nan` should be used instead.
The newest Matplotlib (v3.6.0) also complains about `plt.colorbar()` called from wrong axes (in another documentation figure), so …
=> Updates for NumPy 2 and Matplotlib 3.9

.travis.yml, CONTRIBUTING.rst, README.rst, appveyor.yml, doc/conf.py, doc/transform_methods/comparison/fig_benchmarks/benchmarks.rst, doc/transform_methods/three_point.rst, setup.py
Let's say explicitly in README that the cylindrical axis for all Abel transforms is vertical, as this is not immediately obvious and keeps confusing some users (for example, #388, #383, #362, and several times before).
There also was a warning in a recent Read the Docs buid (for #387):
> WARNING: Calling get_html_theme_path is deprecated. If you are calling it to define html_theme_path, you are safe to remove that code.
treated as a build error (due to ``fail_on_warning: true``), so I've just removed that ``get_html_theme_path()``, as suggested.
The supported Python versions are also updated up to 3.13 (released this month) — the tests pass locally on my system, and hopefully are already supported by Travis and AppVeyor.
And, last but not least, I've updated the rotten/moved external …
=> Cylindrical axis orientation in README; refreshed external URLs, RTD config, Python versions

.github/workflows/pytest.yml
Here is the first step to address #365 — using GitHub Actions to run the unit tests on Linux, macOS and Windows (regular Python instead of Anaconda).
* As I understand, this [should be free for public projects](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions), but even in the worst case we should be allowed 2000 minutes per month (not too much, taking into account that macOS counts at 10× rate, but probably enough).
* Python 2.7 is not tested because it's apparently not available (and we should get rid of it anyway), but it's still covered by AppVeyor.
* For Python 3, only the lowest (3.7) and highest (3.13) versions form “PyAbel requires Python 3.7–3.13” are tested. I think, this should be enough, …
=> GitHub Actions to run pytest

abel/transform.py
The current documentation notation describing how the symmetrize_method=="average" function works, is misleading. It says things like "Q01 = Q0 + Q1", indicating that the combination is a summation of Q0 and Q1. Instead it is either or, if only one of the quadrants is specified by use_quadrants, or it is the average of the two quadrants is specified. This commit expands the documentation to eliminate the misleading language.
=> Update docs: remove misleading notation surrounding quadrant averaging

.github/workflows/pytest.yml, CHANGELOG.rst, abel/tests/test_tools_polynomial.py, abel/tests/test_tools_vmi.py, abel/tools/math.py, abel/tools/vmi.py, doc/conf.py
Investigation of the spurious errors and warnings in CI tests (#391) revealed that:
1. New Apple's hardware (arm64) have larger floating-point errors.
2. The default method `'lm'` in `scipy.optimize.curve_fit()` is broken (see SciPy [#21995](https://github.com/scipy/scipy/issues/21995)) and thus was producing `OptimizeWarning` in _some_ testing environments; more importantly, it could produce wrong estimates for fitting errors.
So this PR changes the method in `curve_fit()` to a well-behaved `'trf'` and also adds tests to ensure that the error estimates returned by `anisotropy_parameter()` are correct. Some tolerances in the tests are also increased slightly to accommodate this change and the sloppier Apple's arm64 performance.
Now all the tests pass cleanly.
The `'trf'` method also …
=> Control off-range beta in `anisotropy_parameter()`; avoid broken SciPy optimizer

.readthedocs.yml
I've got an email from Read the Docs about
> deprecation of projects using Sphinx or MkDocs without an explicit configuration
(see [here](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) for details).
So here is the explicit configuration.
Plus normalized indentation.
=> Update for Read the Docs

.github/workflows/info.py, .github/workflows/pytest.yml, .github/workflows/sdist.yml, .github/workflows/wheels.yml, MANIFEST.in, examples/README.txt, setup.py
Here is the next step in moving from Travis CI to GitHub Actions (#365):
* Building the source distribution (sdist) and also testing that it can be installed with and without Cython.
* Building binary distributions (wheels, with the Cython extension) again, but now for
* Linux (amd64),
* macOS (amd64 and arm64),
* Windows (amd64).
The wheels are built using [cibuildwheel](https://github.com/pypa/cibuildwheel) (apparently the official tool), as [suggested](https://github.com/PyAbel/PyAbel/issues/365#issuecomment-1336233250) by @rth. Although it supports more platforms, not all are actually provided (for free) by GitHub Actions, plus NumPy and SciPy themselves don't have binary packages for everything (x86 Linux is an example), so probably covering the most popular ones will be good enough. …
=> GitHub actions to build sdist and wheels

README.rst, doc/conf.py, doc/conf/mathjax.py, doc/readme_link.rst, doc/tools/polynomial.rst
In preparation for the new release (#401), here are corrections to some problems noticed in the docs:
1. “Able-transformed” → “Abel-transformed” (a common typo, but seems to be the only occurrence in the repository).
2. “PyAbel includes the following transform methods” in README was always linking to the _latest_ RTD version, even for other RTD versions and when built locally. Now it is replaced in `doc/readme_link.rst` accordingly, like other such links.
3. The MathJax download link stopped working, so it had to be updated.
=> Minor documentation updates
